add new function to sequence_list_generator.py and modify sequence_generator.py
mimosa-project/intseq pull request #11
Opened 2024-01-15 08:01 UTC by a073ffu

数列の選別を行うsortingの関数をsequence_list_generator.pyへ追加。
また、sequence_generator.pyに起きていた、comprの無限ループ対策を追加。
実行時間の都合で現在compr_implの最大ループ数を10に設定しているので、要調整。
sequence_generator.pyのDivision,Modのmod0などの計算不能な数式に遭遇した時、エラーを返すように変更。
プルリクエスト#6をマージ

2024-01-15 08:19 UTC, aabaa requested changes

2024-01-15 08:19 UTC, aabaa commented on src/sequence_generator.py
> +        max_iter = 10
これはなぜ10としたのでしょうか？その根拠をコメントしてください．

2024-01-15 08:19 UTC, aabaa commented on src/sequence_generator.py
> +    def compr_impl(f:Callable[[int, int], int], a:int, max_iter:int) -> int:
max_iterのデフォルト引数を-1として，-1であれば無限ループを許容する形にしてください．

2024-01-15 08:19 UTC, aabaa commented on src/sequence_generator.py
> +        self.rpn = self.str2rpn(rpn)
str2rpn()は__init__の外で使うことを想定しているのでココで呼ばないでください．
__init__()の中に入れてしまうと，rpnがリスト形式のときに処理できなくなるからです．

2024-01-15 08:19 UTC, aabaa commented on src/sequence_list_generator.py
> +    max_num_of_loops=1000 # 下のwhile文の最大ループ回数
最大ループ数を1000とした理由をコメントしてください
ここでマジックナンバーとなる定数を宣言するべきではなく，generate関数の引数とするべきです．

2024-01-15 08:19 UTC, aabaa commented on src/sequence_generator.py
> +    def compr_impl(f:Callable[[int, int], int], a:int, max_iter:int) -> int:
max_iterはクラスComprのメンバ変数としてください

2024-01-15 08:19 UTC, aabaa commented on src/sequence_list_generator.py
> +        a=random.randint(1, max_num_of_loops)
whileの内部でaの値を毎回書き換えることに違和感があります．

2024-01-15 08:19 UTC, aabaa commented on src/sequence_list_generator.py
> +def sorting():
コメントと関数名が合っていません

2024-01-15 11:26 UTC, a073ffu commented on src/sequence_generator.py
> +        max_iter = 10
これは、私のノートパソコンの性能だとmax_iterの数値が大きくなるとループ回数が多くなりすぎて、実行時間が長くなりすぎて大変だったからです。
compr_implの性能的にはmax_iterは大きいほうが良いと思いますが、max_iter=10の時点で数列100個作るのに20分近くかかったので、プログラムを見直すか、max_iterを小さくする必要があると思います。

2024-01-15 11:40 UTC, a073ffu commented on src/sequence_list_generator.py
> +    max_num_of_loops=1000 # 下のwhile文の最大ループ回数
yが束縛されている数列をランダム生成したときの定数関数の割合が、
最大ループ数が100と1000の場合でほぼ変わらなかったため、
最大ループ数は生成される数列の種類にあまり関係ないと判断して特に気にしていませんでした。
しかし、現状の生成される数列を見ているとほとんどがy=ax+bの単純な数列ばかりなので、
下手に最大ループ数が多いと数列に見合わない大きさの複雑度が設定される可能性があるため、
小さい方がいいかもしれないです。
最大ループ数が小さい場合でも数列を生成してみて、どんな数列が生成されるのか試してみます。

2024-01-16 05:17 UTC, aabaa requested changes

2024-01-16 05:17 UTC, aabaa commented on src/sequence_generator.py
> +    def compr_impl(f:Callable[[int, int], int], a:int, max_iter:int) -> int:
max_iterは引数から除外する
staticmethodは外してself.max_iterでアクセスする

2024-01-16 05:17 UTC, aabaa commented on src/sequence_generator.py
> +        self.max_iter = max_iter
__init__ではmax_iterはセットしない

2024-01-16 05:17 UTC, aabaa commented on src/sequence_generator.py
> +            while m < max_iter or m > max_iter:
m < max_iter or max_iter == -1:

2024-01-16 05:17 UTC, aabaa commented on src/sequence_generator.py
> +    def __init__(self, rpn, max_iter=None):
max_iter=-1

2024-01-16 05:17 UTC, aabaa commented on src/sequence_list_generator.py
> +    while(random.randint(1, max_num_of_loops)>n):
loop_num = random.randint(1, max_loop_num)
while n < loop_num:

2024-01-16 05:17 UTC, aabaa commented on src/sequence_list_generator.py
> +def sort_out_sequence(max_num_of_loops, max_iter=-1):
select_sequenceとかfilter_sequence

2024-01-16 05:17 UTC, aabaa commented on src/sequence_list_generator.py
> +                        break
```python
if (determine_y_is_bound(stack) and
    not determine_a_constant_sequence(stack) and
    not determine_no_information_amount(stack)):
    return sequence, information_amount
```

2024-01-16 05:17 UTC, aabaa commented on src/sequence_list_generator.py
> +    return sequence, information_amount
消す

2024-01-16 05:17 UTC, aabaa commented on src/sequence_list_generator.py
> +        return True
```python
def check_if_y_is_bound(sequence_stack):
    return  'y' not in sequence_stack[0].find_free_variables()
```

2024-01-16 05:17 UTC, aabaa commented on src/sequence_list_generator.py
> +        return False
```python
def check_if_constant_sequence(sequence_stack):
    # 10個を確認して全て一致すれば定数関数として除外
```

2024-01-16 05:17 UTC, aabaa commented on src/sequence_list_generator.py
> +        return False
```python
# 初項0,公差1の等差数列(1,2,3,...)かどうかをチェックする
def check_if_arithmetic_progression(stack):
    for i in range(0, 10):
        if(stack[0].calc(i, 0) != i):
            return False
    return True
```

2024-01-16 05:18 UTC, aabaa commented
sequence_generator.py -> program.py
sequence_list_generator.py -> sequence_generator.py
にリネームする(git renameを使うこと)

2024-01-17 04:16 UTC, aabaa requested changes

2024-01-17 04:16 UTC, aabaa commented on src/sequence_generator.py
> +        letter2variation = {'A':1, 'B':1, 'C':1, 'D':-1, 'E':-1, 'F':-1, 'G':-1, 'H':-1, 'I':-2, 'J':-2, 'K':1, 'L':1, 'M':-1, 'N':-4}
関数呼び出しの度に生成されるべきではないので，VARIATION_OF_PROGRAM_NUMと同じ場所にクラスの定数として定義してください．
LETTER_TO_VARIATION = {'A':1, 'B':1, 'C':1, 'D':-1, 'E':-1, 'F':-1, 'G':-1, 'H':-1, 'I':-2, 'J':-2, 'K':1, 'L':1, 'M':-1, 'N':-4}

2024-01-17 04:16 UTC, aabaa commented on src/sequence_generator.py
> +# 必要な数列を選別
「必要な」ではなく「適切な」

2024-01-17 04:16 UTC, aabaa commented on src/sequence_generator.py
> +def check_if_arithmetic_progression(stack):
check_if_arithmetic_progression -> check_if_trivial_arithmetic_progression
arithmetic_progressionだと全ての等比数列が対象になってしまうので

2024-01-17 08:42 UTC, aabaa approved these changes

2024-01-19 04:22 UTC, merged